export const WHATSAPP_NUMBER = "918090191817";
export const FIRM_NAME = "PRG & Associates";
export const FIRM_TAGLINE = "Your Trusted Financial Partner";
export const FIRM_EMAIL = "prgtax@gmail.com";
export const FIRM_PHONE = "+91 80901 91817";
export const FIRM_ADDRESS = "Nishatganj, Lucknow";

export const SERVICES = [
  {
    id: "gst",
    icon: "FileText",
    title: "GST Registration & Filing",
    description: "Complete GST solutions including registration, monthly/quarterly returns, GST audit, and compliance management.",
    features: ["GST Registration", "GSTR-1, 3B Filing", "GST Audit", "GST Refund"],
    color: "from-blue-500 to-blue-700",
  },
  {
    id: "itr",
    icon: "Calculator",
    title: "Income Tax Return (ITR)",
    description: "Hassle-free ITR filing for individuals, businesses, and corporates with maximum tax savings.",
    features: ["Individual ITR", "Business ITR", "Tax Planning", "TDS Returns"],
    color: "from-green-500 to-green-700",
  },
  {
    id: "company",
    icon: "Building2",
    title: "Company Registration",
    description: "End-to-end company incorporation services for Private Limited, LLP, OPC, and Partnership firms.",
    features: ["Pvt Ltd Company", "LLP Registration", "OPC Formation", "Partnership Deed"],
    color: "from-purple-500 to-purple-700",
  },
  {
    id: "accounting",
    icon: "BookOpen",
    title: "Accounting & Bookkeeping",
    description: "Professional accounting, bookkeeping, and financial statement preparation services.",
    features: ["Bookkeeping", "P&L Statement", "Balance Sheet", "MIS Reports"],
    color: "from-indigo-500 to-indigo-700",
  },
  {
    id: "audit",
    icon: "ClipboardCheck",
    title: "Audit & Assurance",
    description: "Statutory audit, internal audit, and tax audit services for businesses of all sizes.",
    features: ["Statutory Audit", "Internal Audit", "Tax Audit", "Stock Audit"],
    color: "from-teal-500 to-teal-700",
  },
  {
    id: "msme",
    icon: "Award",
    title: "MSME / Udyam Registration",
    description: "Register your business under MSME/Udyam to avail government benefits and subsidies.",
    features: ["Udyam Certificate", "MSME Benefits", "Priority Lending", "Govt Schemes"],
    color: "from-yellow-500 to-yellow-700",
  },
  {
    id: "food",
    icon: "UtensilsCrossed",
    title: "Food License (FSSAI)",
    description: "FSSAI registration and license for food businesses, restaurants, and food manufacturers.",
    features: ["Basic Registration", "State License", "Central License", "License Renewal"],
    color: "from-orange-500 to-orange-700",
  },
  {
    id: "trademark",
    icon: "Shield",
    title: "Trademark Registration",
    description: "Protect your brand identity with trademark registration and intellectual property services.",
    features: ["TM Search", "TM Application", "TM Objection", "TM Renewal"],
    color: "from-red-500 to-red-700",
  },
  {
    id: "labour",
    icon: "HardHat",
    title: "Labour Registration",
    description: "Complete labour law compliance including PF, ESIC, PT, and labour license registration.",
    features: ["PF Registration", "ESIC Registration", "Professional Tax", "Labour License"],
    color: "from-rose-500 to-rose-700",
  },
  {
    id: "tds",
    icon: "FileMinus",
    title: "TDS Filing",
    description: "Accurate and timely TDS return filing for individuals, businesses, and corporates.",
    features: ["Form 24Q", "Form 26Q", "TDS Certificate", "TDS Correction"],
    color: "from-cyan-500 to-cyan-700",
  },
  {
    id: "tcs",
    icon: "FilePlus",
    title: "TCS Filing",
    description: "Tax Collected at Source filing and compliance for sellers and collectors as per Income Tax Act.",
    features: ["Form 27EQ", "TCS Certificate", "TCS Reconciliation", "TCS Compliance"],
    color: "from-violet-500 to-violet-700",
  },
  {
    id: "iso",
    icon: "BadgeCheck",
    title: "ISO Certification",
    description: "ISO 9001, 14001, 22000 and other certifications to boost your business credibility globally.",
    features: ["ISO 9001:2015", "ISO 14001", "ISO 22000", "HACCP"],
    color: "from-emerald-500 to-emerald-700",
  },
  {
    id: "iec",
    icon: "Globe",
    title: "Import Export Code (IEC)",
    description: "IEC registration for businesses involved in import/export of goods and services from India.",
    features: ["IEC Registration", "IEC Modification", "DGFT Compliance", "Export Benefits"],
    color: "from-sky-500 to-sky-700",
  },
  {
    id: "ngo",
    icon: "Heart",
    title: "NGO / Society / Trust Registration",
    description: "Complete registration of NGOs, societies, trusts, and Section 8 companies with 12A & 80G benefits.",
    features: ["Society Registration", "Trust Deed", "Section 8 Company", "12A & 80G"],
    color: "from-pink-500 to-pink-700",
  },
  {
    id: "dsc",
    icon: "KeyRound",
    title: "DSC Registration",
    description: "Digital Signature Certificate (DSC) for individuals and organizations for e-filing and online transactions.",
    features: ["Class 3 DSC", "DGFT DSC", "DSC Renewal", "e-Tendering DSC"],
    color: "from-lime-500 to-lime-700",
  },
  {
    id: "startup",
    icon: "Rocket",
    title: "Startup India Registration",
    description: "Get recognized under Startup India scheme and avail tax exemptions, funding, and government benefits.",
    features: ["DPIIT Recognition", "Tax Exemption", "Funding Support", "IPR Benefits"],
    color: "from-orange-400 to-orange-600",
  },
  {
    id: "business-consultancy",
    icon: "TrendingUp",
    title: "Business Consultancy",
    description: "Strategic business advisory, financial planning, and growth consulting for startups and SMEs.",
    features: ["Business Planning", "Financial Advisory", "Growth Strategy", "Valuation"],
    color: "from-teal-600 to-teal-800",
  },
  {
    id: "finance-consultancy",
    icon: "DollarSign",
    title: "Finance Consultancy",
    description: "Expert financial consulting to help businesses optimize cash flow, investments, and long-term financial strategy.",
    features: ["Financial Planning", "Investment Advisory", "Cash Flow Management", "Risk Assessment"],
    color: "from-blue-500 to-cyan-700",
  },
  {
    id: "legal",
    icon: "Scale",
    title: "Legal Services",
    description: "End-to-end legal support including drafting agreements, legal notices, and contract management.",
    features: ["Agreement Drafting", "Legal Notice", "Contract Review", "MOU Drafting"],
    color: "from-slate-500 to-slate-700",
  },
  {
    id: "loan",
    icon: "Banknote",
    title: "Loan Services",
    description: "Assistance in securing business loans, home loans, MUDRA loans, and government-backed financing.",
    features: ["Business Loan", "MUDRA Loan", "Home Loan", "Project Finance"],
    color: "from-green-600 to-green-800",
  },
  {
    id: "projected-bs",
    icon: "BarChart3",
    title: "Projected Balance Sheet",
    description: "Preparation of projected financial statements for bank loans, investors, and business planning.",
    features: ["Projected P&L", "Cash Flow Statement", "Fund Flow", "CMA Data"],
    color: "from-purple-600 to-purple-800",
  },
  {
    id: "billing-software",
    icon: "Receipt",
    title: "Customized Billing Software",
    description: "Tailor-made billing and invoicing software solutions designed to fit your specific business workflow.",
    features: ["Custom Invoicing", "GST-Ready Bills", "Payment Tracking", "Multi-User Access"],
    color: "from-emerald-500 to-green-700",
  },
  {
    id: "accounting-software",
    icon: "BookMarked",
    title: "Customized Accounting Software",
    description: "Bespoke accounting software tailored to your business needs for seamless financial management.",
    features: ["Ledger Management", "Auto Reconciliation", "Financial Reports", "Cloud Access"],
    color: "from-violet-500 to-indigo-700",
  },
];

export const STATS = [
  { value: "500+", label: "Happy Clients" },
  { value: "12+", label: "Years Experience" },
  { value: "25+", label: "Services Offered" },
  { value: "99%", label: "Client Satisfaction" },
];

export const TEAM = [
  {
    name: "Advocate Pawan Yadav",
    role: "Partner - Corporate Affairs",
    qualification: "ACA, CS",
    experience: "10+ Years",
    specialization: "Legal Services",
  },
  {
    name: "Mr. Rahul Sharma",
    role: "Founder & CEO",
    qualification: "FCA, DISA",
    experience: "12+ Years",
    specialization: "Taxation & Audit",
  },
  {
    name: "CA Gaurav",
    role: "Partner - GST & Indirect Tax",
    qualification: "ACA, LLB",
    experience: "8+ Years",
    specialization: "GST & Indirect Taxation",
  },
];

export const TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    business: "Restaurant Owner",
    text: "PRG & Associates helped me get my FSSAI license and GST registration within days. Truly excellent and fast service!",
    rating: 5,
  },
  {
    name: "Sunita Mehta",
    business: "E-commerce Entrepreneur",
    text: "Their ITR filing service saved me a significant amount of tax. Very professional and knowledgeable team.",
    rating: 5,
  },
  {
    name: "Amit Joshi",
    business: "Startup Founder",
    text: "Company registration was seamless. They guided me through every step. Highly recommended for any startup!",
    rating: 5,
  },
  {
    name: "Pooja Agarwal",
    business: "Boutique Owner",
    text: "Got my trademark registered without any hassle. The team is very responsive and thorough in their work.",
    rating: 5,
  },
  {
    name: "Vikram Singh",
    business: "Manufacturing Unit",
    text: "GST audit and compliance handled perfectly. No penalties, no stress. PRG & Associates is our go-to firm.",
    rating: 5,
  },
  {
    name: "Meera Nair",
    business: "NRI Client, Dubai",
    text: "Managing my Indian investments and ITR from abroad was a challenge until I found PRG. They handle everything remotely!",
    rating: 5,
  },
  {
    name: "Deepak Verma",
    business: "Pharma Distributor",
    text: "MSME registration and drug license both done within a week. Exceptional speed and accuracy. Truly reliable!",
    rating: 5,
  },
  {
    name: "Anita Desai",
    business: "School Principal",
    text: "Society registration and 80G certification done smoothly. The team understands NGO compliance very well.",
    rating: 5,
  },
  {
    name: "Rohit Malhotra",
    business: "Real Estate Developer",
    text: "Tax planning and audit services are top-notch. Saved lakhs in taxes with their smart financial advice.",
    rating: 5,
  },
];
